language: node_js
env:
 - db__host=127.0.0.1
before_install:
 - sudo add-apt-repository ppa:rethinkdb/ppa -y && sudo apt-get update -y && sudo apt-get install rethinkdb -y
before_script:
 - rethinkdb --daemon
install:
 - npm install
 - npm install mocha -g
node_js:
 - "4"